### ISSUE TITLE
add 3d model

### ISSUE THREAD

**Issue by s-light** [adafruit/Adafruit-QT-Py-ESP32-S3-PCB#1]
is it possible to add a 3d model ?
maybe directly exported from eagle?

i think this are the needed details:

- board outline
- usb-c connector position and outline/height
- STEMMA QT connector position and outline/height
- button positions/height
- battery solder-pad positions
- neopixel position/height

[adafruit forum post](https://forums.adafruit.com/viewtopic.php?t=201244)

**Comment by caternuson** [comment]
This guides covers how to generate 3D files from the Eagle files:
https://learn.adafruit.com/how-to-convert-eagle-pcbs-to-3d-models-in-fusion-360

**Comment by s-light** [comment]
as pointed out in the forum thread:
you can use 
https://github.com/adafruit/Adafruit_CAD_Parts/tree/main/5325%20QTPy%20ESP32S2
for most of us this should be identically enough ;-)
